apiVersion: v1
kind: Template
metadata:
  name: hccm-frontend-mods
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: cost-management-mfe
    spec:
      envName: ${ENV_NAME}
      title: 'Federated Modules for Cost Management'
      deploymentRepo: https://github.com/project-koku/koku-ros-ui
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/cost-management-mfe
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - title: ROS for Cost Management
          expandable: true
          routes:
            - appId: 'cost-management-mfe'
              title: Overview
              href: "/openshift/cost-management-mfe"
            - appId: 'cost-management-mfe'
              title: 'OpenShift'
              href: '/openshift/cost-management-mfe/ocp'
      module:
        manifestLocation: "/apps/cost-management-mfe/fed-mods.json"
        modules:
          - id: "cost-management-mfe"
            module: "./RootApp"
            routes:
              - pathname: /openshift/cost-management-mfe
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/hccm-frontend-mods
